blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/Aimony/lumina/discussions/new?category=q-a
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/Aimony/lumina/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=
    about: Share ideas for new features
  - name: Report a bug
    url: https://github.com/Aimony/lumina/issues/new?assignees=&labels=bug&template=bug_report.md&title=
    about: Report a reproducible bug
